### ISSUE TITLE
CustomEvent error on IE 11

### ISSUE THREAD

**Issue by Yann77** [ahlechandre/mdl-stepper#14]
Hi ahlechandre !!

First, thanks for this nice implementation of MDL stepper.
Second, we are experiencing an error in IE that prevent us from using it...

SCRIPT445: Object doesn't support this action
This error occurred as soon as you define CustomEvents.

I did some search and one workaround for IE >= 9 compatibility would be to use document.createEvent() and CustomEvent::initCustomEvent()

Here are the sources:
https://github.com/sindresorhus/devtools-detect/issues/9
http://stackoverflow.com/questions/19345392/why-arent-my-parameters-getting-passed-through-to-a-dispatched-event/19345563#19345563

Would you plan doing this fix shortly ?

Regards,
Yannick Richard

**Comment by axdemelas** [comment]
Hi @Yann77,

Thanks for letting me know. It will be resolved on next release.

**Comment by Yann77** [comment]
Thanks for the fast answer !! This is great news.
Can I ask when the next release is planned ?

**Comment by axdemelas** [comment]
@Yann77 May be today or tomorrow.

**Comment by axdemelas** [comment]
IE still scaring me.

![ie-scaring](https://cloud.githubusercontent.com/assets/7119058/16122124/525ccc02-33bc-11e6-8133-4c074429d76d.jpg)

**Comment by Yann77** [comment]
That's a short schedule !! I am happy about it since we unfortunately still need to support IE 11 at least... I think support is better with Edge and even better with Chrome.

Thanks for your time !!!

**Comment by axdemelas** [comment]
@Yann77 New changes at master. Currently, I do not have access to the IE platform. You can clone and check if the error persists?

I chose to use the [MDN polyfill](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent#Polyfill). Look at: https://github.com/ahlechandre/mdl-stepper/blob/master/src/stepper/stepper.js#L8

**Comment by Yann77** [comment]
Hi @ahlechandre !

When I npm install lastest 1.1.3 version, I cannot see your latest changes in stepper.js for polyfill ??? It is there on github and I use right mdl-stepper in package.json, I don't get it ;-)

I did npm cache clean, delete everything from node-module, it seems that I am experiencing some npm cache problem...

Regards,
Yannick Richard

**Comment by Yann77** [comment]
I think you forgot to publish latest on NPM repo. I was able to grab your latest from github with 'npm install github:ahlechandre/mdl-stepper --save' but I would like to use npm package name if possible.

Please let me know when npm repo is up to date.

Thanks a lot !

**Comment by axdemelas** [comment]
Hi @Yann77 

After fixes #12 I published the `v1.1.4` at NPM. Check out new release. 

Closing this issue now and if needed I can reopen.

**Comment by sucre666** [comment]
Hi,

SCRIPT445: Object doesn't support this action
Error still occurs on IE 11, could you check this once again?

**Comment by russell-tarpley** [comment]
Confirmed. I am still seeing SCRIPT445: Object doesn't support this action on IE 11 using version 1.1.5

**Comment by russell-tarpley** [comment]
My testing in IE 11 seems to point at the mdn CustomEvent polyfill code that you added seems to cause issues in material.js, particularly around upgradeElement as CustomEvent is defined for window by the polyfill. I receive errors anytime I have stepper.js included when trying to use upgradeElement (even on other components). I took a look at the code in material.js and if I use the same conditional logic they use for CustomEvents in stepper.js the issue goes away.

This was just a quick experiment but it avoids injecting global code that may impact other components/functionality and no longer encounters errors in IE 11...
1. I commented out the CustomEvent polyfill code
2. I created a helper function:
   `MaterialStepper.prototype.DefineCustomEvent = function (ev, bubble, cancel) {
         var ev;
         if ('CustomEvent' in window && typeof window.CustomEvent === 'function') {
             ev = new Event(ev, {
                 'bubbles': bubble, 'cancelable': cancel
             });
         } else {
             ev = document.createEvent('Events');
             ev.initEvent(ev, bubble, cancel);
         }
         return ev;
     };`

3.And used the helper function to assign the custom events
`MaterialStepper.prototype.CustomEvents_ = {
          onstepnext: MaterialStepper.prototype.DefineCustomEvent('onstepnext', true, true),
          onstepcancel: MaterialStepper.prototype.DefineCustomEvent('onstepcancel', true, true),
          onstepskip: MaterialStepper.prototype.DefineCustomEvent('onstepskip', true, true),
          onstepback: MaterialStepper.prototype.DefineCustomEvent('onstepback', true, true),
          onstepcomplete: MaterialStepper.prototype.DefineCustomEvent('onstepcomplete', true, true),
          onsteperror: MaterialStepper.prototype.DefineCustomEvent('onsteperror', true, true),
          onsteppercomplete: MaterialStepper.prototype.DefineCustomEvent('onsteppercomplete', true, true)
      };`

**Comment by axdemelas** [comment]
@Rathxxx nice point, I'll do some tests and implement to the master. Do you want to send it as PR?
